### ISSUE TITLE
exceptions that occur during graph execution are not visible to users

### ISSUE THREAD

**Issue by liorella-qm** [entropy-lab/entropy#204] opened 2022-04-12 11:04 UTC
when I run an experiment using `entropylab.graph_experiment.Graph.run`, any exception that occurs inside the nodes leads to a runtime error which contains no information about the exception that was actually caught, making it very difficult to obtain information about the error.

**Comment by galwiner** [comment] 2022-04-12 11:51
This is a duplicate of https://github.com/entropy-lab/entropy/issues/75
I'll close #75 and keep this one.

**Comment by galwiner** [comment] 2022-04-12 19:14
I've attempted to recreate by putting a `raise ValueError` line in a node payload. 
The error seems to be raised without issue. 
@liorella-qm can we try to recreate together?

**Comment by SatyaBade12** [comment] 2022-04-24 11:36
for the sake of completeness, here is a small example to reproduce the bug, it **only** happens when we delete the .db files of `ExperimentResources`.

```
from entropylab import *
import os

path = "."
os.makedirs(path, exist_ok=True)

db_files = [".entropy/params.db", ".entropy/entropy.db", ".entropy/entropy.hdf5"]

for file in db_files:
    if os.path.exists(file):
        os.remove(file)

experiment_resources = ExperimentResources(SqlAlchemyDB(path))

def root_node():
    print("root node")
    print(a)
    return {}

node0 = PyNode(label="root_node", program=root_node)

experiment = Graph(resources=experiment_resources,graph={node0}, story="run_a")
handle = experiment.run()
```
@qguyk  says [line 16](https://github.com/entropy-lab/entropy/blob/main/entropylab/results_backend/sqlalchemy/alembic/env.py#:~:text=fileConfig(config.config_file_name)) in the file following file is causing the problem

**Comment by urig** [comment] 2022-04-25 10:44
I can confirm @qguyk's analysis about Alembic's call to `fileConfig(config.config_file_name)` in `env.py` as the likely culprit. This function seems to disable non-Alembic loggers by default. 

I wouldn't be surprised if this is also the root cause of https://github.com/entropy-lab/entropy/issues/134.

A resolution suggested by @galwiner and test by me could be:
`fileConfig(config.config_file_name, , disable_existing_loggers=False)`

Implemented in [PR 213](https://github.com/entropy-lab/entropy/pull/213).

**Closed** 2022-04-25 12:47 UTC
Labels: bug
